### ISSUE TITLE
np.linalg.solve is slow

### ISSUE THREAD

**Issue by zqwei** [bogovicj/JaneliaMLCourse#1]
To my surprise, `np.linalg.solve` is extremely slow running on J-cluster.

conda 4.5.11
numpy                     1.15.0          py36_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
numpy-base                1.14.3           py36h0ea5e3f_1
numpydoc                  0.8.0                    py36_0

![screen shot 2018-09-13 at 2 13 23 pm](https://user-images.githubusercontent.com/13616597/45507262-8d961700-b75f-11e8-86c0-a83054dad842.png)

**Comment by bogovicj** [comment]
Interesting, I wonder...

**Comment by zqwei** [comment]
I wonder too... it surprised me and I repeat this many times, which turned out similar

**Comment by bogovicj** [comment]
That was going to be my next question ( if something about the matrix made it hard to solve - its a random matrix which should be fine most of the time).  

It seems likely then, that its something about the cluster machines.

**Comment by zqwei** [comment]
The blas library? That is the reason I put conda and numpy info as your references.

**Comment by bogovicj** [comment]
I'll try to reproduce.

**Comment by bogovicj** [comment]
I get
```
slow time: 4.5670485496521
fast time: 3.658784866333008 
```

with this environment:
```
    blas:            1.1-openblas                          conda-forge
    bzip2:           1.0.6-h470a237_2                      conda-forge
    ca-certificates: 2018.8.24-ha4d7672_0                  conda-forge
    certifi:         2018.8.24-py36_1                      conda-forge
    libffi:          3.2.1-hfc679d8_5                      conda-forge
    libgcc-ng:       7.2.0-hdf63c60_3                      conda-forge
    libgfortran:     3.0.0-1                               conda-forge
    libstdcxx-ng:    7.2.0-hdf63c60_3                      conda-forge
    ncurses:         6.1-hfc679d8_1                        conda-forge
    numpy:           1.15.0-py36_blas_openblashd3ea46f_200 conda-forge [blas_openblas]
    openblas:        0.2.20-8                              conda-forge
    openssl:         1.0.2p-h470a237_0                     conda-forge
    pip:             18.0-py36_1                           conda-forge
    python:          3.6.6-h5001a0f_0                      conda-forge
    readline:        7.0-haf1bffa_1                        conda-forge
    setuptools:      40.2.0-py36_0                         conda-forge
    sqlite:          3.24.0-h2f33b56_1                     conda-forge
    tk:              8.6.8-0                               conda-forge
    wheel:           0.31.1-py36_1                         conda-forge
    xz:              5.2.4-h470a237_1                      conda-forge
    zlib:            1.2.11-h470a237_3                     conda-forge
```

So, yea, linsolve isnt that much faster, but it also isn't taking 40 seconds!! 

My laptop used mkl, that could be making the difference...

**Comment by zqwei** [comment]
it is not my point to compare np.linalg.solve across different BLAS. MKL or OpenBlas.

I mean it should not be called as a faster solver if it is improved little comparing to np.linalg.inv. This is just misleading.

**Comment by bogovicj** [comment]
> it is not my point to compare np.linalg.solve across different BLAS. MKL or OpenBlas.

I'd say "incomplete" rather than "misleading."  There was no subtlety in the lecture, that's for sure, but I maintain that `solve` is better than `inv` in most cases.  If you need the inverse matrix, then ya, by all means, use `inv`.  

I know you're mathematically savvy, and I'm happy to talk details if you're interested (to the best of my ability).  I have a Numerical Analysis book you can borrow if interested.
